name: assets_management
description: "Application to management assets in a company"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Utils
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/svg/
  
  fonts:
    - family: TractianIcons
      fonts:
        - asset: assets/fonts/TractianIcons.ttf

    - family: RobotoVariable
      fonts:
        - asset: assets/fonts/RobotoVariable.ttf
